JUDGE0_TELEMETRY_ENABLE=false
ENABLE_WAIT_RESULT=true
ENABLE_COMPILER_OPTIONS=false
ENABLE_COMMAND_LINE_ARGUMENTS=false
ENABLE_CALLBACKS=false
ENABLE_BATCHED_SUBMISSIONS=true
USE_DOCS_AS_HOMEPAGE=true

INTERVAL=0.1
COUNT=2
MAX_QUEUE_SIZE=100

ALLOW_ORIGIN=*

REDIS_HOST=judge0-redis
REDIS_PORT=6379
REDIS_PASSWORD=judge0_redis_local_password

POSTGRES_HOST=judge0-db
POSTGRES_PORT=5432
POSTGRES_DB=judge0
POSTGRES_USER=judge0
POSTGRES_PASSWORD=judge0_postgres_local_password

# CPU_TIME_LIMIT=5
# MAX_CPU_TIME_LIMIT=15
# WALL_TIME_LIMIT=10
# MAX_WALL_TIME_LIMIT=20
# MEMORY_LIMIT=256000
# MAX_MEMORY_LIMIT=512000
# STACK_LIMIT=64000
# MAX_STACK_LIMIT=128000
# MAX_PROCESSES_AND_OR_THREADS=60
# MAX_MAX_PROCESSES_AND_OR_THREADS=120
ENABLE_PER_PROCESS_AND_THREAD_TIME_LIMIT=false
ENABLE_PER_PROCESS_AND_THREAD_MEMORY_LIMIT=false
ALLOW_ENABLE_NETWORK=false
ENABLE_NETWORK=false
ENABLE_CGROUP=false

RAILS_ENV=production
RAILS_MAX_THREADS=4
RAILS_SERVER_PROCESSES=2
SECRET_KEY_BASE=replace_this_with_a_long_random_string_before_production
